config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'users/new', to: 'users#new', as: 'new_user'
  get '/signup',   to:  'users#new'
  get '/signin',   to:  'sessions#new'
  post '/signin',  to:  'sessions#create'
  delete '/signout', to: 'sessions#destroy', as: 'session'

  resources :users, only: [:create]

  
  root to: "products#index"
  # we can't have a comment without a product,
  # so comments resource is NESTED in products resource
  resources :products do
    resources :comments, only: [:create]
  end

  # get '/products',          to: 'products#index'
  # get '/products/new',      to: 'products#new', as: 'new_product'
  # get '/products/:id',      to: 'products#show', as: 'product'
  # post '/products',         to: 'products#create'
  # get '/products/:id/edit', to: 'products#edit', as: 'edit_product'
  # patch '/products/:id',    to: 'products#update'
  # delete '/products/:id',   to: 'products#destroy'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true

  belongs_to :product
  belongs_to :user

  default_scope { order(created_at: :desc) }
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :description, presence: true
  validates :price, numericality: { 
    greater_than: 0.0
  }
  validates :quantity, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0
  }


  belongs_to :user

  #add dependent destroy so when product is deleted,
  # its corresponding comments will be deleted as well
  has_many :comments, dependent: :destroy

  def owned_by?(owner) 
    user == owner
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, :last_name, presence: true
  validates :email, 
    presence: true, 
    uniqueness: { case_sensitive: false },
    format: { 
      with: /\A[A-Z0-9#-_~!$&'()*+,;=:.]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i 
    }

  has_many :products, dependent: :destroy

  has_secure_password

  before_save :downcase_email

  def fullname
    "#{first_name} #{last_name}"
  end

  private

  def downcase_email
    self.email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def current_user
    @current_user ||= User.find_by(id: cookies.signed[:user_id])
  end

  def require_signin
    unless current_user
      flash[:alert] = "Please sign in first"
      redirect_to signin_path
    end
  end

  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_signin
  before_action :set_product

  def create
    #get product object first, and use it to create comment
    @comment = @product.comments.build(comment_params)
    @comment.user = current_user
    # the above is the same as @comment.user.id = current_user.id

    if @comment.save
      flash[:notice] = "Comment has been created"
      redirect_to @product

      #this is a redirect to product show page.
      # @product is a shortcut for product_path(@product.id)
    else
      @comments = @poduct.comments
      flash.now[:alert] = "Comment has not been created"
      render 'products/show'
    end
  end

  private

  def set_product
    # there will be only one product in this array 
    # created below, so we can just take the first (and only)
    #element to retrieve it.
    @product = Product.where(id: params[:product_id]).first
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :require_signin, except: [:index, :show]
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  before_action :require_owner, only: [:edit, :update, :destroy]
  def index
    @products = Product.all
  end

  def show
    @comment = @product.comments.build
    
    #get all comments associated with a particular product to display those comments
    @comments = @product.comments
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    # associate products with owner
    @product.user = current_user
    if @product.save
      flash.now[:notice] = "Product has been saved successfully"
      redirect_to root_path
    else
      flash[:alert] = "Product has not been saved. Please try again"
      render :new
    end
  end

  def edit
 
  end

  def update
    
    if @product.update(product_params)
      flash.now[:notice] = "Product has been updated successfully"
      redirect_to root_path
    else
      flash[:alert] = "Product has not been updated.  Please try again"
      render :edit
    end
  end

  def destroy
   
    @product.destroy
    redirect_to root_path
  end

  private

  def require_owner
    unless @product.owned_by?(current_user)
      flash[:alert] = "Access denied"
      redirect_to root_path
    end
  end

  def find_product
    begin
    @product = Product.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
    end
  end

  def product_params
    params.require(:product).permit(
      :name, :price, :description, 
      :image_url, :quantity
      )
  end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_path if current_user
  end

  def create
    # 1. find user by email address and downcase it
    user = User.find_by( email: params[:email].downcase )

    # 2. Check if the user can be authenticated using the password provided
    if user && user.authenticate(params[:password])
      cookies.signed[:user_id] = user.id
      flash[:notice] = "Sign in successful!"
      redirect_to root_path
    else
      flash.now[:alert] = "Invalid email/password combination"
      render :new
    end  
    # 3. If a user is found and authenticated, then set signed cookie

    # 4. Otherwise, set alert message and render new form
  end

  def destroy
    cookies.delete :user_id
    flash[:notice] = "You have been signed out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if current_user
      flash[:notice] = "You have already signed up"
      redirect_to root_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # next line implements automatic sign in upon sign up
      cookies.signed[:user_id] = @user.id
      flash[:notice] = "Signed up successfully"
      redirect_to root_path
    else  
      flash.now[:alert] = "Sign up failed"
      render :new
    end
  end

    private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
  end

  

app/helpers/application_helper.rb
module ApplicationHelper

  def commented_by(user)
    user.fullname
  end  

  def persisted_comments(comments)
    # reject comments that have not been saved with reject
    comments.reject{ |comment| comment.new_record? }
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="col-md-10 offset-md-1 comment-block mt-4">
          <div class="comment-body mb-2 mt-3">
            <%= comment.body %>
          </div>
          <small>
            <em> 
              Created 
                <span>
                <%= "#{time_ago_in_words(comment.created_at)}" %>
                </span>  ago by: 
                </em>
            <%= "#{ commented_by comment.user}" %>
          </small>
        </div>

app/views/comments/_form.html.erb
<div class="row">
  <div class="col-md-10 offset-md-1 reviews-form">
    <h1 class="text-center form-header-style mt-5 pt-2 pb-3">
      Add Comments
    </h1>

    <div class="form-body-style px-5 pt-4">
      <%= form_with(model: [product, comment], local: true) do |f| %>
        <%= render 'shared/errors', object: comment %>

        <div class='form-group row'>
          <div class="col-md-2 col-form-label">
            <%= f.label :body, 'New Comment' %>
          </div>
          <div class='col-md-9'>
            <%= f.text_area :body,
                row: '5',
                class: "form-control",
                placeholder: "Your comment",
                autofocus: true
            %>
          </div>
        </div>

        <div class='form-group row'>
          <div class='offset-md-2 col-md-9'>
            <%= f.submit class: "btn btn-outline-purple btn-lg" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OSale</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'hello_react' %> 
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/messages' %>

    <div id='root'></div>

    <%= yield %>  

  <%= render 'shared/footer' %>

    
  </body>
</html>

app/views/products/_form.html.erb
<div class="form-body-style px-5 pt-4">
  <%= form_with model: @product, local: true do |f| %>
    
      
     <%= render 'shared/errors', object: @product %>

        <div class="form-group row">
      <div class="col-md-3 col-form-label">
        <%= f.label :name %>
      </div>
      <div class="col-md-9">
        <%= 
          f.text_field :name, 
          class: "form-control", 
          placeholder: "Product name", 
          autofocus: true 
        %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-md-3 col-form-label">
        <%= f.label :price %>
      </div>
      <div class="col-md-9">
        <%= 
          f.text_field :price, 
          class: "form-control", 
          placeholder: "Product price" 
        %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-md-3 col-form-label">
        <%= f.label :description %>
      </div>
      <div class="col-md-9">
        <%= 
          f.text_area :description, 
          class: "form-control", 
          placeholder: "Product description",
          rows: '5'
        %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-md-3 col-form-label">
        <%= f.label :quantity %>
      </div>
      <div class="col-md-9">
        <%= 
          f.number_field :quantity, 
          class: "form-control", 
          placeholder: "Product quantity" 
        %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-md-3 col-form-label">
        <%= f.label :image_url, 'Image' %>
      </div>
      <div class="col-md-9">
        <%= 
          f.file_field :image_url, 
          class: "form-control"
        %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-md-9 offset-md-3">
      <%= f.submit class: "btn btn-outline-purple" %>
      </div>
    </div>

  <% end %>
</div>

app/views/products/_product.html.erb
<div class="col-md-4 col-sm-6 col-xs-12 mb-4">
              <div class="card">
                <img class="card-img-top img-fluid" src="http://placehold.it/140x100" alt="Card image cap">
                <div class="card-body">
                  <h5 class="card-title">
                    <span class="badge badge-pill badge-purple float-right">
                    <%= number_to_currency(product[:price]) %>
                    </span>
                    <%= link_to product[:name], product_path(product.id) %>
                  </h5>
                  <p class="card-text">
                    <%= truncate(product[:description], length: 150) %>
                  </p>
                </div>
              </div>
            </div>

app/views/products/edit.html.erb
    <div class="container mb-4">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="card panel-div">
          <h1 class="text-center form-header-style pt-2 pb-3">
            Edit Product
          </h1>

          <%= render 'form' %>
          
        </div>
      </div>
    </div>
  </div>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="jumbotron">
      <h1 class="display-4">Welcome to <span class="goog">O-Sale</span> online market place!</h1>
      <p class="lead">Lorem ipsum dolor sit amet,consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
  </div>
</div>

<div class="container">
    <div class="row">
      <div class="col-md-12 mb-2">
        <div class="row">
          <div class="card-deck">
            <% @products.each do |product| %>
              <%= 
                  render partial: 'product', 
                  locals: { product: product } 
              %>
           <% end %>
           
          </div>
        </div>
      </div>
    </div> <!-- row -->
  </div> <!-- container -->

app/views/products/new.html.erb
    <div class="container mb-4">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="card panel-div">
          <h1 class="text-center form-header-style pt-2 pb-3">
            Add New Product
          </h1>

          <div class="form-body-style px-5 pt-4">
            <%= form_with model: @product do |f| %>
              <div class="form-group row">
                <div class="col-md-3 col-form-label">
                  <%= f.label :name %>
                </div>
                <div class="col-md-9">
                  <%= 
                    f.text_field :name, 
                    class: "form-control", 
                    placeholder: "Product name", 
                    autofocus: true 
                  %>
                </div>
              </div>

              <div class="form-group row">
                <div class="col-md-3 col-form-label">
                  <%= f.label :price %>
                </div>
                <div class="col-md-9">
                  <%= 
                    f.text_field :price, 
                    class: "form-control", 
                    placeholder: "Product price" 
                  %>
                </div>
              </div>

              <div class="form-group row">
                <div class="col-md-3 col-form-label">
                  <%= f.label :description %>
                </div>
                <div class="col-md-9">
                  <%= 
                    f.text_area :description, 
                    class: "form-control", 
                    placeholder: "Product description",
                    rows: '5'
                  %>
                </div>
              </div>

              <div class="form-group row">
                <div class="col-md-3 col-form-label">
                  <%= f.label :image_url, 'Image' %>
                </div>
                <div class="col-md-9">
                  <%= 
                    f.file_field :image_url, 
                    class: "form-control"
                  %>
                </div>
              </div>

              <div class="form-group row">
                <div class="col-md-9 offset-md-3">
                <%= f.submit class: "btn btn-outline-purple" %>
                </div>
              </div>

            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/products/show.html.erb
  <div class="container">
    <div class="row">
      <div class="col-md-10 offset-md-1">
        <img class="img-fluid" src="http://placehold.it/350x150" width="100%">
      </div>
  
      <div class="col-md-10 offset-md-1">
        <div class="float-right">
          <h3><span class="badge badge-pill badge-purple">
            <%= number_to_currency(@product.price) %></span>
          </h3>
        </div>
        <div>
          <h3><%= @product.name %></h3>
        </div>
  
        <div class="mb-4">
          <%= @product.description %>
        </div>
  
        <% if current_user && @product.owned_by?(current_user) %>
          <div class="float-right btn-edit-del">
            <%= 
              link_to "Delete", 
              product_path(@product),
              method: :delete,
              data: { confirm: "Are you sure you want to delete?" },
              class: "btn btn-outline-danger btn-lg"
            %>
          </div>
  
          <div class="btn-edit-del">
            <%= 
              link_to "Edit", 
              edit_product_path(@product), 
              class: "btn btn-outline-purple btn-lg" 
            %>
          </div>
        <% end %>
      </div>
    </div>

    <%= 
      render partial: 'comments/form',
      locals: { product: @product, comment: @comment }
    %>
    <div class="row">
        <div class="col-md-10 offset-md-1 mt-4">
          <h2 class="comment-header">Customer comments (<%= @comments.count %>)</h2>
        </div>
        
         <! --below, the reject method rejects all records that have not been saved
        before doing the for each. -->
        
        <% persisted_comments(@comments).each do |comment| %>
           <%= render partial: 'comments/comment', object: comment %>
        <% end %>
            
  </div>
  

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
           <div id="error_explanation">
             <h5 class="card-title">
               <%= pluralize(object.errors.count, "error") %>
               prohibited this <%= object.class.name.humanize.downcase %> from being saved
             </h5>
             <ul>
               <% object.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
             </ul>
           </div>
          <% end %>

app/views/shared/_footer.html.erb
<footer class="text-center">
  Copyright &copy; 2020 Donny Lobree
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light ">
      <%= link_to "O-Sale", root_path, class: "navbar-brand goog" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to root_path, class: "nav-link" do %>
              Home <span class="sr-only">(current)</span>
            <% end %>
          </li>

          <% unless current_user %>
            <li class="nav-item">
              <%= link_to "Sign In", signin_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Up", signup_path, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "New Product", new_product_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Out", session_path, method: :delete, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <p class="navbar-text">Signed in as <%= current_user.email %></p>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

app/views/shared/_messages.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success text-center" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>  


<% if flash[:alert] %>
  <div class="alert alert-danger text-center" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>  

app/views/users/new.html.erb
<div class="container mt4">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <!-- <div className="card panel-div"> -->
        <h1 class="text-center form-header-style mt-5 pt-2 pb-3">
          Sign Up
        </h1>

        <div class="form-body-style px-5 pt-4">
          <%= form_with model: @user, local: true do |f| %>
            <%= render 'shared/errors', object: @user %>

            <div class="form-group row">
              <div class="col-md-2 col-form-label">
                <%= f.label :first_name %>
              </div>
              <div class="col-md-9">
                <%= 
                  f.text_field :first_name, 
                  class: "form-control", 
                  placeholder: "Your first name", 
                  autofocus: true 
                %>
              </div>
            </div>

            <div class="form-group row">
              <div class="col-md-2 col-form-label">
                <%= f.label :last_name %>
              </div>
              <div class="col-md-9">
                <%= 
                  f.text_field :last_name, 
                  class: "form-control", 
                  placeholder: "Your last name" 
                %>
              </div>
            </div>

            <div class="form-group row">
              <div class="col-md-2 col-form-label">
                <%= f.label :email %>
              </div>
              <div class="col-md-9">
                <%= 
                  f.email_field :email, 
                  class: "form-control", 
                  placeholder: "Your email address" 
                %>
              </div>
            </div>

            <div class="form-group row">
              <div class="col-md-2 col-form-label">
                <%= f.label :password %>
              </div>
              <div class="col-md-9">
                <%= f.password_field :password, 
                  class: "form-control", 
                  placeholder: "Your password here" 
                %>
              </div>
            </div>

            <div class="form-group row">
              <div class="col-md-9 offset-md-2">
                <%= f.submit 'Sign up', class: "btn btn-outline-purple" %>
              </div>
            </div>
          <% end %>
        </div>
      <!-- </div> -->
    </div>
  </div>
</div>